name: Clone GNU Hurd Repos

on:
  workflow_dispatch:
  push:
    paths:
      - 'clone-repos.sh'
      - '.github/workflows/clone-repos.yml'

jobs:
  clone-gnu-hurd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Ensure git is installed
      run: sudo apt-get update && sudo apt-get install -y git

    - name: Run clone-repos.sh
      run: |
        chmod +x clone-repos.sh
        ./clone-repos.sh
      env:
        GIT_TERMINAL_PROMPT: 0

    - name: Upload CLONE_STATUS.txt
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: CLONE_STATUS
        path: external/CLONE_STATUS.txt

#    - name: Upload Log Output
#      if: failure()
#      run: echo "Clone script failed" > clone-failure.log
#      uses: actions/upload-artifact@v4
#      with:
#        name: clone-failure-log
#        path: clone-failure.log
