name: Clone Hurd Main

on:
  workflow_dispatch:

jobs:
  clone-gnu-hurd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Ensure git is installed
      run: sudo apt-get update && sudo apt-get install -y git

    - name: Run clone-repos
      run: |
        cd external
        git clone --progress https://git.savannah.gnu.org/git/hurd.git
